from pathlib import Path

OUTPUT_DIRECTORY = Path("data/processed")
BM25_DIRECTORY = OUTPUT_DIRECTORY / "bm25"
CHROMA_DIRECTORY = OUTPUT_DIRECTORY / "chroma"

CHUNKS_METADATA_PATH = OUTPUT_DIRECTORY / "chunks_metadata.json"
MANIFEST_PATH = OUTPUT_DIRECTORY / "manifest.json"

MAX_BATCH_SIZE: int = 1024
DEFAULT_CHUNK_SIZE: int = 2000

EMBEDDING_MODEL: str = (
    # "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    # "intfloat/multilingual-e5-small"
    "all-MiniLM-L6-v2"
)
TRANSLATION_MODEL: str = (
    "Helsinki-NLP/opus-mt-mul-en"
)
LLM_MODEL = "Qwen/Qwen3-0.6B"

DEFAULT_VLLM: str = "data/raw/vllm-0.10.1"

DEFAULT_DATASET_FILE_NAME: str = "dataset_code_public.json"

DEFAULT_DATA_DIRECTORY: str = "data"
DEFAULT_DATASET_DIRECTORY: str = f"{DEFAULT_DATA_DIRECTORY}/datasets"
DEFAULT_OUTPUT_DIRECTORY: str = f"{DEFAULT_DATA_DIRECTORY}/output"

DEFAULT_UNANSWERED_QUESTIONS_DIRECTORY: str = (
    f"{DEFAULT_DATASET_DIRECTORY}/UnansweredQuestions"
)
DEFAULT_ANSWERED_QUESTIONS_DIRECTORY: str = (
    f"{DEFAULT_DATASET_DIRECTORY}/AnsweredQuestions"
)

DEFAULT_UNANSWERED_QUESTIONS_PATH: str = (
    f"{DEFAULT_UNANSWERED_QUESTIONS_DIRECTORY}/{DEFAULT_DATASET_FILE_NAME}"
)
DEFAULT_ANSWERED_QUESTIONS_PATH: str = (
    f"{DEFAULT_ANSWERED_QUESTIONS_DIRECTORY}/{DEFAULT_DATASET_FILE_NAME}"
)

DEFAULT_SEARCH_RESULTS_DIRECTORY: str = (
    f"{DEFAULT_OUTPUT_DIRECTORY}/search_results"
)
DEFAULT_ANSWER_RESULTS_DIRECTORY: str = (
    f"{DEFAULT_OUTPUT_DIRECTORY}/search_results_and_answer"
)

DEFAULT_SEARCH_RESULTS_PATH: str = (
    f"{DEFAULT_SEARCH_RESULTS_DIRECTORY}/{DEFAULT_DATASET_FILE_NAME}"
)
DEFAULT_ANSWER_RESULTS_PATH: str = (
    f"{DEFAULT_ANSWER_RESULTS_DIRECTORY}/{DEFAULT_DATASET_FILE_NAME}"
)

DEFAULT_DATASET_PATH: str = DEFAULT_UNANSWERED_QUESTIONS_PATH
DEFAULT_SAVE_DIRECTORY: str = DEFAULT_SEARCH_RESULTS_DIRECTORY
DEFAULT_RESULTS_PATH: str = DEFAULT_SEARCH_RESULTS_PATH
DEFAULT_ANSWER_DIRECTORY: str = DEFAULT_ANSWER_RESULTS_DIRECTORY
DEFAULT_STUDENT_ANSWER_PATH: str = DEFAULT_SEARCH_RESULTS_PATH
